# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: postgresql
  encoding: unicode
  username: ali
  password: 'shah'
  pool: 5
  host: localhost
  port: 5432

development:
  <<: *default
  database: eventspaces_development

test:
  <<: *default
  database: eventspaces_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>